version: "3"

services:
  # Nginx proxy for api Airline
  nginx:
    image: nginx:latest
    container_name: airline_nginx
    depends_on:
      - api
    volumes:
      - ./docker/api.conf:/etc/nginx/conf.d/default.conf    # nginx conf
      - ./data/nginx/logs:/var/log/nginx                          # logs
      - api_public:/app/public              # move uploads files from airline_api
    ports:
      - 8080:80

  # Airline api
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: airline_api_dev
    container_name: airline_api
    volumes:
      - ./:/app
      - api_public:/app/public
    env_file:
      - .env
    depends_on:
      - mysql

  # MySQL container
  mysql:
    image: mysql
    container_name: airline_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  # Adminer for MySQL and MongoDB
  adminer:
    image: adminer
    container_name: airline_adminer
    restart: always
    ports:
      - 8081:8080  # port for adminer 8081

volumes:
  api_public: